apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kube-system

resources:
  - https://raw.githubusercontent.com/kubernetes-sigs/headlamp/main/kubernetes-headlamp.yaml
  - serviceaccount.yaml
  - clusterrolebinding.yaml
  - secret.yaml
  - ingress.yml
