# my global config
global:
  scrape_interval: 15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

remote_write:
  - url: "http://mimir:9009/api/v1/push"

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.

scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  #- job_name: 'tube.nobell.fr'
  #  static_configs:
  #    - targets: ['10.2.50.56:9091']

  - job_name: 'pve-exporter'
    static_configs:
      - targets: ["10.0.50.5:9221", "212.227.203.142:9221"]  # Proxmox VE node with PVE exporter.
    metrics_path: /pve
    params:
      module: [default]
      cluster: ['1']
      node: ['1']

  - job_name: 'ha.nobell.fr'
    scrape_interval: 15s
    metrics_path: /api/prometheus
    authorization:
      credentials: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiIxYWE3NmZiY2Y5OGQ0ODE3YmZmZjRmZDlmOTY1NjQ2MiIsImlhdCI6MTc1NjY3NzEwNSwiZXhwIjoyMDcyMDM3MTA1fQ.G4Y9Y5kihzE6QnhVqkfQYzxmK_upv3J2hrn96tGFXNk"

    scheme: http
    static_configs:
      - targets: ['10.0.21.12:8123']

  - job_name: 'vil.rtr.nbl.sh'
    scrape_interval: 15s
    metrics_path: /metrics
    basic_auth:
      username: prometheus
      password: KX7tfLUo6aD2pWI31C87zYYmbK3fwJJS
    scheme: http
    static_configs:
      - targets: ['10.2.30.1:9273']

        #  - job_name: 'vyos_exporter_frr'
        #    scrape_interval: 15s
        #    metrics_path: /metrics
        #    scheme: http
        #    static_configs:
        #      - targets: ['10.2.50.1:9432']

        #  - job_name: 'vyos_exporter_node_exporter'
        #    scrape_interval: 15s
        #    metrics_path: /metrics
        #    scheme: http
        #    static_configs:
        #      - targets: ['10.2.50.1:9100']
  - job_name: 'truenas.int.enpos.fr'
    scrape_interval: 15s
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets: ['127.0.0.1:9108']

  - job_name: 'ssl_exporter'
    scrape_interval: 5m
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets: ['185.157.245.181:9069']

  - job_name: 'node_exporter'
    scrape_interval: 15s
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets:
        - 10.0.50.12:9100
        - 10.2.50.11:9100
        - 10.2.50.55:9100
        - 10.2.50.61:9100
        - 10.2.50.62:9100
        - 10.2.50.63:9100
        - 10.2.50.100:9100
        - 10.2.50.102:9100
        - 10.2.50.155:9100
        - 10.2.51.21:9100
        - 10.2.51.22:9100
        - 10.2.51.23:9100
        - 10.2.51.24:9100
        - 10.2.51.25:9100
        - 10.0.22.11:9100
        - 10.0.22.13:9100
        - 10.0.22.14:9100
        - 10.2.21.101:9100
        - 10.2.21.102:9100
        - 45.90.160.57:9100
        - 185.157.245.181:9100
        - 217.154.95.84:9100
        - 45.59.122.223:9100
        - 217.174.245.242:9100

  - job_name: 'headscale_exporter'
    scrape_interval: 15s
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets: ['45.90.160.57:9090']

  - job_name: 'xmpp.nobell.fr'
    scrape_interval: 15s
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets: ['10.2.4.7:5280']
