---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mimir
  namespace: mimir
  labels:
    app: mimir
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mimir
  template:
    metadata:
      labels:
        app: mimir
    spec:
      containers:
        - name: mimir
          image: grafana/mimir:2.13.1
          args:
            - "-config.file=/etc/mimir.yaml"
            - "-target=all"
            - "-config.expand-env=true"
          ports:
            - containerPort: 9009
              name: http
          env:
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: mimir-s3-secret
                  key: AWS_SECRET_ACCESS_KEY
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: mimir-s3-secret
                  key: AWS_ACCESS_KEY_ID
          volumeMounts:
            - name: mimir-config
              mountPath: /etc/mimir.yaml
              subPath: mimir.yaml
      volumes:
        - name: mimir-config
          configMap:
            name: mimir-config
