apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mimir

resources:
  - deployment.yml
  - secrets.yml
  - volumes.yml
  - ingress.yml

configMagGenerator:
  - name: mimir-config
    files: 
      - config.yaml=mimir.yaml

