---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mimir-s3-secret
  namespace: mimir
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: mimir-s3-secret
    creationPolicy: Owner
  data:
    - secretKey: AWS_SECRET_ACCESS_KEY
      remoteRef:
        key: s3/mimir
        property: secret_key
    - secretKey: AWS_ACCESS_KEY_ID
      remoteRef:
        key: s3/mimir
        property: access_key
