apiVersion: v1
kind: Namespace
metadata:
  name: nextcloud
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: nextcloud-secrets
  namespace: nextcloud
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: nextcloud-secrets
    creationPolicy: Owner
  data:
    - secretKey: NC_PASSWORD_SALT
      remoteRef:
        key: nextcloud
        property: password_salt
    - secretKey: NC_SECRET
      remoteRef:
        key: nextcloud
        property: secret
    - secretKey: NC_DB_PASSWORD
      remoteRef:
        key: postgresql/users
        property: nextcloud_user
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-config
  namespace: nextcloud
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-csi
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-data
  namespace: nextcloud
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-csi
  resources:
    requests:
      storage: 500Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextcloud
  namespace: nextcloud
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nextcloud
  template:
    metadata:
      labels:
        app: nextcloud
    spec:
      securityContext:
        fsGroup: 33
        fsGroupChangePolicy: "OnRootMismatch"
      containers:
        - name: nextcloud
          image: nextcloud:33.0.3
          ports:
            - containerPort: 80
          envFrom:
            - secretRef:
                name: nextcloud-secrets
          volumeMounts:
            - name: nextcloud-data
              mountPath: /nextcloud-data
            - name: nextcloud-config
              mountPath: /var/www/html/config/
      volumes:
        - name: nextcloud-data
          persistentVolumeClaim:
            claimName: nextcloud-data
        - name: nextcloud-config
          persistentVolumeClaim:
            claimName: nextcloud-config
---
apiVersion: v1
kind: Service
metadata:
  name: nextcloud
  namespace: nextcloud
spec:
  type: LoadBalancer
  loadBalancerIP: 10.2.51.115
  selector:
    app: nextcloud
  ports:
    - name: http
      port: 80
      targetPort: 80
