---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authentik-secrets
  namespace: authentik
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: authentik-secrets
    creationPolicy: Owner
  data:
    - secretKey: AUTHENTIK_SECRET_KEY
      remoteRef:
        key: kv/authentik
        property: secret_key
    - secretKey: AUTHENTIK_POSTGRESQL__PASSWORD
      remoteRef:
        key: kv/postgresql/users
        property: authentik_user
    - secretKey: AUTHENTIK_STORAGE__MEDIA__S3__ACCESS_KEY
      remoteRef:
        key: kv/s3/authentik
        property: access_key
    - secretKey: AUTHENTIK_STORAGE__MEDIA__S3__SECRET_KEY
      remoteRef:
        key: kv/s3/authentik
        property: secret_key
    - secretKey: AUTHENTIK_BOOTSTRAP_PASSWORD
      remoteRef:
        key: kv/authentik
        property: bootstrap_password
    - secretKey: AUTHENTIK_BOOTSTRAP_TOKEN
      remoteRef:
        key: kv/authentik
        property: bootstrap_token
