---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: homepage-config
  namespace: homepage
spec:
  accessModes:
    - ReadWriteMany   # important pour NFS

  storageClassName: nfs-csi

  resources:
    requests:
      storage: 1Gi
