apiVersion: v1
kind: Namespace
metadata:
  name: frigate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: frigate-media
  namespace: frigate
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-csi
  resources:
    requests:
      storage: 100Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: frigate-config
  namespace: frigate
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-csi
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frigate
  namespace: frigate
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frigate
  template:
    metadata:
      labels:
        app: frigate
    spec:
      containers:
        - name: frigate
          image: ghcr.io/blakeblackshear/frigate:0.17.1
          ports:
            - name: web
              containerPort: 5000
            - name: go2rtc
              containerPort: 1984
            - name: rtsp
              containerPort: 8554
            - name: webrtc-tcp
              containerPort: 8555
          volumeMounts:
            - name: media
              mountPath: /media
            - name: config
              mountPath: /config
            - name: shm
              mountPath: /dev/shm
          securityContext:
            privileged: true
      volumes:
        - name: media
          persistentVolumeClaim:
            claimName: frigate-media
        - name: config
          persistentVolumeClaim:
            claimName: frigate-config
        - name: shm
          emptyDir:
            medium: Memory
            sizeLimit: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: frigate
  namespace: frigate
spec:
  type: LoadBalancer
  loadBalancerIP: 10.2.51.116
  selector:
    app: frigate
  ports:
    - name: web
      port: 5000
      targetPort: 5000
    - name: go2rtc
      port: 1984
      targetPort: 1984
    - name: rtsp
      port: 8554
      targetPort: 8554
    - name: webrtc-tcp
      port: 8555
      targetPort: 8555
