---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frigate
  namespace: frigate
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frigate
  template:
    metadata:
      labels:
        app: frigate
    spec:
      containers:
        - name: frigate
          image: ghcr.io/blakeblackshear/frigate:0.17.1
          ports:
            - name: web
              containerPort: 5000
            - name: go2rtc
              containerPort: 1984
            - name: rtsp
              containerPort: 8554
            - name: webrtc-tcp
              containerPort: 8555
          volumeMounts:
            - name: media
              mountPath: /media
            - name: config
              mountPath: /config
            - name: shm
              mountPath: /dev/shm
          securityContext:
            privileged: true
      volumes:
        - name: media
          persistentVolumeClaim:
            claimName: frigate-media
        - name: config
          persistentVolumeClaim:
            claimName: frigate-config
        - name: shm
          emptyDir:
            medium: Memory
            sizeLimit: 256Mi
