apiVersion: v1
kind: Namespace
metadata:
  name: glance
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: glance
  namespace: glance
spec:
  replicas: 1
  selector:
    matchLabels:
      app: glance
  template:
    metadata:
      labels:
        app: glance
    spec:
      containers:
        - name: glance
          image: glanceapp/glance:latest
          ports:
            - containerPort: 8080
          envFrom:
            - secretRef:
                name: glance-secrets
          volumeMounts:
            - name: glance-config
              mountPath: /app/config
              readOnly: true
            - name: glance-assets
              mountPath: /app/assets
      volumes:
        - name: glance-config
          configMap:
            name: glance-config
        - name: glance-assets
          configMap:
            name: glance-assets
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: glance-secrets
  namespace: glance
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: glance-secrets
    creationPolicy: Owner
  data:
    - secretKey: SECRET_KEY
      remoteRef:
        key: "glance/prod1"
        property: "secret_key"
    - secretKey: ADMIN_PASSWORD
      remoteRef:
        key: "glance/prod1"
        property: "admin_password"
    - secretKey: USER_PASSWORD
      remoteRef:
        key: "glance/prod1"
        property: "user_password"
---
apiVersion: v1
kind: Service
metadata:
  name: glance
  namespace: glance
spec:
  type: LoadBalancer

  selector:
    app: glance

  ports:
    - name: http
      port: 80
      targetPort: 8080
